services:
  app:
    build: .
    container_name: totp-backend

    # Only mount folders you actually need, do NOT mount ./app over /app
    volumes:
      - ./cron:/app/cron      # if you need to edit cron files locally
      - ./scripts:/app/scripts

    ports:
      - "8080:8080"

    # Optional: restart policy
    restart: unless-stopped
