version: "3.9"

services:
  app:
    build: .
    container_name: totp-backend
    ports:
      - "8080:8080"
    volumes:
      - seed-data:/data
      - cron-output:/cron
      - ./app:/app:ro   # mounts entire app folder
    environment:
      TZ: UTC
    restart: unless-stopped

volumes:
  seed-data:
  cron-output:
