services:
  app:
    build: .
    container_name: totp-backend

    volumes:
      - ./cron:/cron:ro
      - ./scripts:/scripts:ro

      - ./app/student_private.pem:/app/student_private.pem:ro
      - ./app/student_public.pem:/app/student_public.pem:ro
      - ./app/instructor_public.pem:/app/instructor_public.pem:ro

      - seed-data:/data
      - cron-output:/cron

    ports:
      - "8080:8080"

    environment:
      - TZ=UTC

    restart: unless-stopped

volumes:
  seed-data:
  cron-output:
